//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.07 at 03:35:10 PM IST 
//


package com.ApiCalling.smarshModel;

import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.datatype.XMLGregorianCalendar;



import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fileDump complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fileDump"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="base64Content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="base64FileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="callInitiator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="callType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="channel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="corporateEmailId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="endTimeUtc" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="fileTransferStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fileTransferedEnd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="loginName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="messageId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="messageType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="network" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="participantEntered" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="roomId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="startTimeUtc" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="threadId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="userFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vendor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

@XmlRootElement(namespace = "com.ApiCalling.smarshModel.FileDump")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fileDump", propOrder = {
		"roomId",
		"base64Content",
    "base64FileName",
    "callInitiator",
    "callType",
    "channel",
    "corporateEmailId",
    "endTimeUtc",
    "fileTransferStatus",
    "fileTransferedEnd",
    "loginName",
    "messageId",
    "messageType",
    "network",
    "participantEntered",
    "roomId",
    "startTimeUtc",
    "status",
    "threadId",
    "userFileName",
    "vendor",
    "fileTransferedStarted",
    "message",
    "participentEntered",
   "fileTranferedEnd",
   "participentExit"
    
    
})
public class FileDump {

	@Id
	 @GeneratedValue(strategy = GenerationType.IDENTITY)
	long fileDumpId;

	protected String roomId;
    protected String base64Content;
    protected String base64FileName;
    protected String callInitiator;
    protected String callType;
    protected String channel;
    protected String corporateEmailId;
    @XmlSchemaType(name = "dateTime")
    protected Date endTimeUtc;
    protected String fileTransferStatus;
    protected String fileTransferedEnd;
    protected String loginName;
    @NotNull
    @Min(message = "quantity cannot be lesser than zero", value = 1)
    protected String messageId;
    protected String messageType;
    protected String network;
    protected String participantEntered;
    
    @XmlSchemaType(name = "dateTime")
    protected Date startTimeUtc;
    protected String status;
    protected String threadId;
    protected String userFileName;
    protected String vendor;
    
   
    
    @NotNull
    List<ParticepentEntered> participentEntered;
    
    
    List<ParticepentExit> participentExit;
    List<FileTransferedStarted> fileTransferedStarted;
List<Message> message;
   List<FileTranferedEnd> fileTranferedEnd;
    public List<FileTransferedStarted> getFileTransferedStarted() {
	return fileTransferedStarted;
}

public void setFileTransferedStarted(List<FileTransferedStarted> fileTransferedStarted) {
	this.fileTransferedStarted = fileTransferedStarted;
}

public List<FileTranferedEnd> getFileTranferedEnd() {
	return fileTranferedEnd;
}

public void setFileTranferedEnd(List<FileTranferedEnd> fileTranferedEnd) {
	this.fileTranferedEnd = fileTranferedEnd;
}

	public List<Message> getMessage() {
	return message;
}

public void setMessage(List<Message> message) {
	this.message = message;
}

	

    public List<ParticepentEntered> getParticipentEntered() {
		return participentEntered;
	}

	public void setParticipentEntered(List<ParticepentEntered> participentEntered) {
		this.participentEntered = participentEntered;
	}

	public List<ParticepentExit> getParticipentExit() {
		return participentExit;
	}

	public void setParticipentExit(List<ParticepentExit> participentExit) {
		this.participentExit = participentExit;
	}

	/**
     * Gets the value of the base64Content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase64Content() {
        return base64Content;
    }

    /**
     * Sets the value of the base64Content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase64Content(String value) {
        this.base64Content = value;
    }

    /**
     * Gets the value of the base64FileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase64FileName() {
        return base64FileName;
    }

    /**
     * Sets the value of the base64FileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase64FileName(String value) {
        this.base64FileName = value;
    }

    /**
     * Gets the value of the callInitiator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallInitiator() {
        return callInitiator;
    }

    /**
     * Sets the value of the callInitiator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallInitiator(String value) {
        this.callInitiator = value;
    }

    /**
     * Gets the value of the callType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallType() {
        return callType;
    }

    /**
     * Sets the value of the callType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallType(String value) {
        this.callType = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannel(String value) {
        this.channel = value;
    }

    /**
     * Gets the value of the corporateEmailId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorporateEmailId() {
        return corporateEmailId;
    }

    /**
     * Sets the value of the corporateEmailId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorporateEmailId(String value) {
        this.corporateEmailId = value;
    }

    /**
     * Gets the value of the endTimeUtc property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getEndTimeUtc() {
        return endTimeUtc;
    }

    /**
     * Sets the value of the endTimeUtc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTimeUtc(Date value) {
        this.endTimeUtc = value;
    }

    /**
     * Gets the value of the fileTransferStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileTransferStatus() {
        return fileTransferStatus;
    }

    /**
     * Sets the value of the fileTransferStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileTransferStatus(String value) {
        this.fileTransferStatus = value;
    }

    /**
     * Gets the value of the fileTransferedEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileTransferedEnd() {
        return fileTransferedEnd;
    }

    /**
     * Sets the value of the fileTransferedEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileTransferedEnd(String value) {
        this.fileTransferedEnd = value;
    }

    /**
     * Gets the value of the loginName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * Sets the value of the loginName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginName(String value) {
        this.loginName = value;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the network property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetwork() {
        return network;
    }

    /**
     * Sets the value of the network property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetwork(String value) {
        this.network = value;
    }

    /**
     * Gets the value of the participantEntered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParticipantEntered() {
        return participantEntered;
    }

    /**
     * Sets the value of the participantEntered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParticipantEntered(String value) {
        this.participantEntered = value;
    }

    /**
     * Gets the value of the roomId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * Sets the value of the roomId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomId(String value) {
        this.roomId = value;
    }

    /**
     * Gets the value of the startTimeUtc property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getStartTimeUtc() {
        return startTimeUtc;
    }

    /**
     * Sets the value of the startTimeUtc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTimeUtc(Date value) {
        this.startTimeUtc = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the threadId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThreadId() {
        return threadId;
    }

    /**
     * Sets the value of the threadId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThreadId(String value) {
        this.threadId = value;
    }

    /**
     * Gets the value of the userFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserFileName() {
        return userFileName;
    }

    /**
     * Sets the value of the userFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserFileName(String value) {
        this.userFileName = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendor(String value) {
        this.vendor = value;
    }

}
