//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.11 at 03:15:04 PM IST 
//


package com.ApiCalling.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fileDump complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fileDump"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="base64Content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="base64FileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="callInitiator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="callType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="channel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="corporateEmailId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="endTimeUtc" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="fileTranferedEnd" type="{}fileTranferedEnd" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="fileTransferStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fileTransferedEnd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fileTransferedStarted" type="{}fileTransferedStarted" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="loginName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="message" type="{}message" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="messageId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="messageType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="network" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="participantEntered" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="participentEntered" type="{}particepentEntered" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="participentExit" type="{}particepentExit" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="roomId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="startTimeUtc" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="threadId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="userFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vendor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fileDump", propOrder = {
		"roomId",
		"base64Content",
    "base64FileName",
    "callInitiator",
    "callType",
    "channel",
    "corporateEmailId",
    "endTimeUtc",
    "fileTranferedEnd",
    "fileTransferStatus",
    "fileTransferedEnd",
    "fileTransferedStarted",
    "loginName",
    "message",
    "messageId",
    "messageType",
    "network",
    "participantEntered",
    "participentEntered",
    "participentExit",
    "roomId",
    "startTimeUtc",
    "status",
    "threadId",
    "userFileName",
    "vendor"
})
@XmlRootElement
public class FileDump {
	@Id
	 @GeneratedValue(strategy = GenerationType.IDENTITY)
	Long id;
     String base64Content;
     String base64FileName;
     String callInitiator;
     String callType;
     String channel;
     String corporateEmailId;
    @XmlSchemaType(name = "dateTime")
     XMLGregorianCalendar endTimeUtc;
    @XmlElement(nillable = true)
     List<FileTranferedEnd> fileTranferedEnd;
     String fileTransferStatus;
     String fileTransferedEnd;
    @XmlElement(nillable = true)
     List<FileTransferedStarted> fileTransferedStarted;
     String loginName;
    @XmlElement(nillable = true)
     List<Message> message;
     String messageId;
     String messageType;
     String network;
     String participantEntered;
    @XmlElement(nillable = true)
     List<ParticepentEntered> participentEntered;
    @XmlElement(nillable = true)
     List<ParticepentExit> participentExit;
     String roomId;
    @XmlSchemaType(name = "dateTime")
     XMLGregorianCalendar startTimeUtc;
     String status;
     String threadId;
     String userFileName;
     String vendor;

    /**
     * Gets the value of the base64Content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase64Content() {
        return base64Content;
    }

    /**
     * Sets the value of the base64Content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase64Content(String value) {
        this.base64Content = value;
    }

    /**
     * Gets the value of the base64FileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase64FileName() {
        return base64FileName;
    }

    /**
     * Sets the value of the base64FileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase64FileName(String value) {
        this.base64FileName = value;
    }

    /**
     * Gets the value of the callInitiator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallInitiator() {
        return callInitiator;
    }

    /**
     * Sets the value of the callInitiator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallInitiator(String value) {
        this.callInitiator = value;
    }

    /**
     * Gets the value of the callType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallType() {
        return callType;
    }

    /**
     * Sets the value of the callType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallType(String value) {
        this.callType = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannel(String value) {
        this.channel = value;
    }

    /**
     * Gets the value of the corporateEmailId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorporateEmailId() {
        return corporateEmailId;
    }

    /**
     * Sets the value of the corporateEmailId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorporateEmailId(String value) {
        this.corporateEmailId = value;
    }

    /**
     * Gets the value of the endTimeUtc property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTimeUtc() {
        return endTimeUtc;
    }

    /**
     * Sets the value of the endTimeUtc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTimeUtc(XMLGregorianCalendar value) {
        this.endTimeUtc = value;
    }

    /**
     * Gets the value of the fileTranferedEnd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the fileTranferedEnd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileTranferedEnd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileTranferedEnd }
     * 
     * 
     */
    public List<FileTranferedEnd> getFileTranferedEnd() {
        if (fileTranferedEnd == null) {
            fileTranferedEnd = new ArrayList<FileTranferedEnd>();
        }
        return this.fileTranferedEnd;
    }

    /**
     * Gets the value of the fileTransferStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileTransferStatus() {
        return fileTransferStatus;
    }

    /**
     * Sets the value of the fileTransferStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileTransferStatus(String value) {
        this.fileTransferStatus = value;
    }

    /**
     * Gets the value of the fileTransferedEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileTransferedEnd() {
        return fileTransferedEnd;
    }

    /**
     * Sets the value of the fileTransferedEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileTransferedEnd(String value) {
        this.fileTransferedEnd = value;
    }

    /**
     * Gets the value of the fileTransferedStarted property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the fileTransferedStarted property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileTransferedStarted().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileTransferedStarted }
     * 
     * 
     */
    public List<FileTransferedStarted> getFileTransferedStarted() {
        if (fileTransferedStarted == null) {
            fileTransferedStarted = new ArrayList<FileTransferedStarted>();
        }
        return this.fileTransferedStarted;
    }

    /**
     * Gets the value of the loginName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * Sets the value of the loginName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginName(String value) {
        this.loginName = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Message }
     * 
     * 
     */
    public List<Message> getMessage() {
        if (message == null) {
            message = new ArrayList<Message>();
        }
        return this.message;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the network property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetwork() {
        return network;
    }

    /**
     * Sets the value of the network property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetwork(String value) {
        this.network = value;
    }

    /**
     * Gets the value of the participantEntered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParticipantEntered() {
        return participantEntered;
    }

    /**
     * Sets the value of the participantEntered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParticipantEntered(String value) {
        this.participantEntered = value;
    }

    /**
     * Gets the value of the participentEntered property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the participentEntered property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParticipentEntered().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParticepentEntered }
     * 
     * 
     */
    public List<ParticepentEntered> getParticipentEntered() {
        if (participentEntered == null) {
            participentEntered = new ArrayList<ParticepentEntered>();
        }
        return this.participentEntered;
    }

    /**
     * Gets the value of the participentExit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the participentExit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParticipentExit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParticepentExit }
     * 
     * 
     */
    public List<ParticepentExit> getParticipentExit() {
        if (participentExit == null) {
            participentExit = new ArrayList<ParticepentExit>();
        }
        return this.participentExit;
    }

    /**
     * Gets the value of the roomId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * Sets the value of the roomId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomId(String value) {
        this.roomId = value;
    }

    /**
     * Gets the value of the startTimeUtc property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTimeUtc() {
        return startTimeUtc;
    }

    /**
     * Sets the value of the startTimeUtc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTimeUtc(XMLGregorianCalendar value) {
        this.startTimeUtc = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the threadId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThreadId() {
        return threadId;
    }

    /**
     * Sets the value of the threadId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThreadId(String value) {
        this.threadId = value;
    }

    /**
     * Gets the value of the userFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserFileName() {
        return userFileName;
    }

    /**
     * Sets the value of the userFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserFileName(String value) {
        this.userFileName = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendor(String value) {
        this.vendor = value;
    }

}
